### ISSUE TITLE
【修改密碼】顯示密碼字元的圖示問題

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#53]
圖示點了沒作用，並且會跳離輸入區域，必須重新輸入字元
![image](https://user-images.githubusercontent.com/52272048/67071842-25adcd80-f1b6-11e9-8ae8-ccee403bf3d1.png)

**Comment by sean31488** [comment]
fixed

**Comment by kay050** [comment]
確認已修改
