### ISSUE TITLE
【老師登入】班級試卷清單功能問題

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#55]
還在批改中的試卷列應不能被點擊，目前點了之後會開啟detail的頁面
![image](https://user-images.githubusercontent.com/52272048/67073562-f26d3d80-f1b9-11e9-9f34-2d5bd3ee10c0.png)

**Comment by sean31488** [comment]
fixed

**Comment by kay050** [comment]
已確認修改
