### ISSUE TITLE
【app】【訂單】進度條顯示問題

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#56]
在訂單尚未被派卷的狀態下，在訂單頁面應呈現0%灰色顯示，目前顯示派卷、複查都是100%
![image](https://user-images.githubusercontent.com/52272048/67184145-ad454780-f415-11e9-901a-25385ea2afe1.png)

**Comment by sean31488** [comment]
fixed

**Comment by kay050** [comment]
已確認修改
