### ISSUE TITLE
【app】【派卷】尚未派卷前，資料呈現問題

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#57]
資料庫測試，將考卷狀態歸零為尚未派卷狀態，在派卷頁面所呈現的資料狀態已是選完老師派完卷的狀態
![image](https://user-images.githubusercontent.com/52272048/67184421-4d9b6c00-f416-11e9-94a2-b5982828a20c.png)

**Comment by sean31488** [comment]
fixed，訂單已初始為已審查(未派卷)

**Comment by kay050** [comment]
在派卷頁面，狀態仍是已選擇完老師，也就是已派卷狀態
![image](https://user-images.githubusercontent.com/52272048/67254809-b1bf3e00-f4b1-11e9-82f5-2b39b1177dcd.png)

**Comment by sean31488** [comment]
當user_id_read為0時，不可顯示已選取
<img width="449" alt="截圖 2019-10-22 下午3 43 37" src="https://user-images.githubusercontent.com/51527447/67266502-fadbb600-f4e2-11e9-9a8e-612fbe7262e3.png">

**Comment by kay050** [comment]
已修改
