### ISSUE TITLE
【app】【複查】detail頁面的圖表座標顯示問題

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#60]
右側座標單位顯示為成0%
![image](https://user-images.githubusercontent.com/52272048/67647111-f5abba80-f96b-11e9-8834-40fb593bc439.png)

**Comment by sean31488** [comment]
這個要前端把Y軸值固定為20%一個間隔，不能以回傳資料來設Y軸值，因為回傳資料可能都為0或不足100

**Comment by kay050** [comment]
前端已調整
