### ISSUE TITLE
【登入】文字顯示修改

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#61]
客戶需求：將保持登入狀態改為記住密碼
![image](https://user-images.githubusercontent.com/52272048/67913444-107a6b00-fbc8-11e9-9fc5-1744d13ad64e.png)

**Comment by sean31488** [comment]
僅修改文字，未修改邏輯，保持登入與記住密碼行為不同

**Comment by kay050** [comment]
已確認
