### ISSUE TITLE
【未登入】【RWD】抽屜式選單顯示問題

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#62]
在尚未登入帳號前，抽屜式選單應顯示：查詢成績/FAQ/Contact us的功能
![image](https://user-images.githubusercontent.com/52272048/67916864-22610b80-fbd2-11e9-98e5-4153d20f1e5a.png)

**Comment by sean31488** [comment]
fixed
增加導航列，顯示規則同pc版右上導航列

**Comment by kay050** [comment]
> fixed
> 增加導航列，顯示規則同pc版右上導航列

需要討論在此抽屜式選單內仍有顯示帳號類別，可能會誤導？是否能將角色身分顯示取消，或者不顯示學生or老師
下方導航列如果調整到上方位置，是否花時間？
![image](https://user-images.githubusercontent.com/52272048/67936681-2c513180-fc07-11e9-9430-f5b99fea39ea.png)

**Comment by sean31488** [comment]
這個是對照設計稿[學生體驗側邊欄_mobile](https://zpl.io/2yPNGjq)，可能參考下設計的意見再調整

**Comment by kay050** [comment]
已補上設計圖，並提供切圖

**Comment by sean31488** [comment]
fixed

**Comment by kay050** [comment]
已確認
