### ISSUE TITLE
【修改密碼】【RWD】顯示的功能問題

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#63]
在輸入密碼時，右邊顯示數字的眼睛按鈕不能點擊，會跳出輸入框
![image](https://user-images.githubusercontent.com/52272048/67917097-e5494900-fbd2-11e9-9f7d-4b49afa6c1df.png)

**Comment by sean31488** [comment]
fixed
因手機長按與滑鼠長按行為不同，調整為點擊切換顯示/不顯示密碼，手機畫面較小，在觸控時容易誤觸輸入框，下次應提醒設計將顯示密碼放在輸入框外

**Comment by kay050** [comment]
確認已修改
