### ISSUE TITLE
【後台】【帳戶維護】功能問題

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#64]
目前帳戶維護下沒有子分類顯示，需要將管理員/派卷主任/閱卷老師/書局/老師/學生的分類顯示出來
![image](https://user-images.githubusercontent.com/52272048/67918070-e16af600-fbd5-11e9-8b92-f8b7f497b605.png)

ppt上標註
![image](https://user-images.githubusercontent.com/52272048/67918098-f34c9900-fbd5-11e9-82c0-2369ac4e5aa4.png)

**Comment by sean31488** [comment]
fixed
增加角色查詢

**Comment by kay050** [comment]
需要客戶確定以角色查詢方式是否合用

**Comment by kay050** [comment]
客戶確認可以
