### ISSUE TITLE
【共通】安全問題增加功能

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#67]
管理後台、前端頁面在登入帳號逾30分鐘，需要設置session失效，強制登出

**Comment by sean31488** [comment]
前後台已增加30分鐘後跳至登入頁規則，須將api開啟token限制後才會生效，app須將該帶token的api帶入token

**Comment by kay050** [comment]
web端測試沒有生效

**Comment by sean31488** [comment]
fixed

**Comment by kay050** [comment]
> fixed

web前端沒有生效，還在登入後的頁面，管理後台已可以

**Comment by sean31488** [comment]
這個不會主動登出，需要任意動作觸發，銀行有交易的那種才會做主動登出
登出 > 重新整理 > 登入 > 放30分鐘 >  點頁面上任意功能

**Comment by kay050** [comment]
已確認
