### ISSUE TITLE
【後台】卷別維護增加功能

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#69]
【卷別】頁面下方增加可維護閱卷標準圖片的功能按鈕，一次可上傳多張圖片、圖片可即時刪除

**Comment by sean31488** [comment]
已新增功能
卷別資料維護 > 卷別 > 新增/修改頁面 右下側
這個必須要有，app還缺api [複查_閱卷標準圖片展開](https://zpl.io/aRGZ94e)
上傳檔案的空間，s3權限有問題，能寫不能讀

**Comment by kay050** [comment]
> 已新增功能
> 卷別資料維護 > 卷別 > 新增/修改頁面 右下側
> 這個必須要有，app還缺api [複查_閱卷標準圖片展開](https://zpl.io/aRGZ94e)
> 上傳檔案的空間，s3權限有問題，能寫不能讀

後台功能已確認；但是目前沒有app部分並沒有上傳檔案的空間嗎？

**Comment by kay050** [comment]
public

**Comment by sean31488** [comment]
調整s3權限，可正常上傳圖片

**Comment by kay050** [comment]
已確認
