### ISSUE TITLE
【通知信件】主旨與內文顯示調整

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#70]
主旨與內文需要改為：
主旨：[大師塾作文批改]密碼重新設定
內文：親愛的用戶您好，請點擊以下連結重新設定密碼。

在內文下方也需要加上超連結，token有效期限為1hr

**Comment by kay050** [comment]
需要告知客戶如何設置mail server，正式交件的時候，需要讓客戶測試運作

**Comment by sean31488** [comment]
調整忘記密碼郵件主旨及內文

**Comment by kay050** [comment]
> 調整忘記密碼郵件主旨及內文

超過1小時，token仍可以使用；應修改為1hr後失效

**Comment by sean31488** [comment]
token過期後修改密碼會失敗，由後端控制，成功修改密碼與失敗的訊息不同，現在設定為5分鐘，確認後修改為60分鐘

**Comment by kay050** [comment]
> token過期後修改密碼會失敗，由後端控制，成功修改密碼與失敗的訊息不同，現在設定為5分鐘，確認後修改為60分鐘

意思是，超過時間，仍可以連結到修改密碼的網址，但是修改密碼會失敗這樣嗎？

**Comment by kay050** [comment]
超過5分鐘，修改密碼會跳回登入頁並提示過期失效，已確認

**Comment by sean31488** [comment]
修改密碼調整為60分鐘過期
