### ISSUE TITLE
【查詢成績】班級成績顯示問題

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#71]
如試卷還在批改中，應不能在下方出現成績結果的細項內容，只能顯示進度
![image](https://user-images.githubusercontent.com/52272048/68107086-9c6cf980-ff1e-11e9-9cce-3067be8cc7a3.png)
![image](https://user-images.githubusercontent.com/52272048/68107117-b1e22380-ff1e-11e9-9a4c-827a6c9ae048.png)

**Comment by sean31488** [comment]
未完成複查不顯示下方詳細資料

**Comment by kay050** [comment]
已確認
