### ISSUE TITLE
【試算結果】計算功能及顯示問題

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#79]
第一輪所有欄位輸入完之後，切換至試算結果頁面出現錯誤
![image](https://user-images.githubusercontent.com/52272048/70492769-7ac7e900-1b40-11ea-8ba8-93c54021a793.png)

**Comment by sean31488** [comment]
調整試算資料驗證行為

**Comment by kay050** [comment]
驗證提示訊息有沒有辦法提示是資料未填還是格式錯誤、輸入數字超過範圍？目前按提示回頭檢查欄位，在都有填寫的情況下，比較難確定是哪種錯誤
可再討論提示內容如何讓使用者更為清楚

**Comment by sean31488** [comment]
目前調整方向:
1. 在輸入時就驗證所有欄位是否正確，若輸入不正確不會進到結果頁
2. 舊資料有錯誤已調整

**Comment by kay050** [comment]
提示需要檢查創辦人出資欄位是否正確，會跳回其中一輪，但不確定是否是跳回有問題的輪次頁面，或只是提示欄位問題，固定跳回最後一輪頁面？檢查最後一輪頁面的欄位為正常
![image](https://user-images.githubusercontent.com/52272048/71157569-342f6880-227d-11ea-9cb4-7ae6c56f49f2.png)

**Comment by kay050** [comment]
按討論的方式製作
