### ISSUE TITLE
【試算結果】儲存記錄按鈕功能問題

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#80]
輸入完檔名后，按下確定，畫面上方出現錯誤提示訊息
![image](https://user-images.githubusercontent.com/52272048/70492962-28d39300-1b41-11ea-959a-0ca7ad7b705c.png)

**Comment by sean31488** [comment]
調整試算資料驗證行為

**Comment by kay050** [comment]
按討論的方式製作
