### ISSUE TITLE
【首頁】文字顯示問題

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#84]
與客戶提供的內容不符
![image](https://user-images.githubusercontent.com/52272048/71434122-f8cde780-271d-11ea-80d2-94dd0ba60515.png)
![image](https://user-images.githubusercontent.com/52272048/71434128-03887c80-271e-11ea-820f-c73827526dd5.png)

**Comment by sean31488** [comment]
更新為客戶提供的文案

**Comment by kay050** [comment]
已確認
