### ISSUE TITLE
【忘記密碼】驗證mail內容顯示問題

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#85]
少了密碼的顯示
![image](https://user-images.githubusercontent.com/52272048/71435978-43536200-2726-11ea-9c57-d59c72ab4615.png)

**Comment by sean31488** [comment]
需要與客戶說明此欄位無意義，因為連結過去就直接改密碼了，在此郵件顯示星號也沒什麼實際作用

**Comment by kay050** [comment]
已同客戶說明
