### ISSUE TITLE
【股權規劃試算】資料顯示問題

### ISSUE THREAD

**Issue by kay050** [kay050/S.KW.C-Studio#86]
不同帳號，新帳號卻顯示其他帳號曾經輸入過的資料
![image](https://user-images.githubusercontent.com/52272048/71436120-e7d5a400-2726-11ea-8b9f-9747c0525c2f.png)

**Comment by sean31488** [comment]
這是規格內的暫存功能，如果需要清除，要列出清除暫存的觸發點，ex: 每次登入後清除etc

**Comment by kay050** [comment]
已確認調整
